# Generated by Django 4.2.23 on 2025-07-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='DD/MM/AAAA', null=True)),
                ('species', models.CharField(choices=[('cat', 'Gato'), ('dog', 'Perro')], default='Gato', max_length=3)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default=('M', 'Macho'), max_length=1)),
                ('color', models.CharField(max_length=50)),
                ('hair', models.CharField(blank=True, choices=[('S', 'Corto'), ('M', 'Mediano'), ('L', 'Largo')], default=('M', 'Mediano'), max_length=50)),
                ('size', models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default=('M', 'Mediano'), max_length=1)),
                ('in_adopt', models.BooleanField(default=True)),
                ('bio', models.TextField(help_text='Datos de la mascota', max_length=250)),
                ('file', models.ImageField(blank=True, upload_to='media')),
                ('status', models.CharField(choices=[('OK', 'Normal'), ('SK', 'Enfermo'), ('DF', 'Fallecido')], default=('SK', 'Enfermo'), max_length=2, null=True)),
                ('owner', models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
