# Generated by Django 5.1 on 2025-06-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre Mascota', models.CharField(max_length=100)),
                ('Fecha nacimiento', models.DateField(blank=True)),
                ('Especie', models.CharField(choices=[('cat', 'Gato'), ('dog', 'Perro')], default=('cat', 'Gato'), max_length=3)),
                ('Raza', models.CharField(blank=True, max_length=50)),
                ('Sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default=('M', 'Macho'), max_length=1)),
                ('Pelaje', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('Tamaño', models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default=('M', 'Mediano'), max_length=1)),
                ('En Adopción', models.BooleanField(default=None)),
                ('bio', models.TextField()),
                ('status', models.CharField(choices=[('OK', 'Normal'), ('SK', 'Enfermo'), ('DF', 'Fallecido')], default=('OK', 'Normal'), max_length=2)),
                ('Dueño', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
