# Generated by Django 5.1 on 2025-06-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='Fecha nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
