# Generated by Django 4.2.23 on 2025-07-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Gato'), ('dog', 'Perro')], default=('cat', 'Gato'), max_length=3),
        ),
    ]
