<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-07-07 05:14
=======
# Generated by Django 4.2.23 on 2025-07-07 05:21
>>>>>>> origin

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
<<<<<<< HEAD
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default=(
                'M', 'Macho'), max_length=5),
=======
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default=('M', 'Macho'), max_length=5),
>>>>>>> origin
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
<<<<<<< HEAD
            field=models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default=(
                'M', 'Mediano'), max_length=5),
=======
            field=models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default=('M', 'Mediano'), max_length=5),
>>>>>>> origin
        ),
    ]
