# Generated by Django 5.1 on 2025-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='Dueño',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='En Adopción',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Especie',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Fecha nacimiento',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Nombre Mascota',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Pelaje',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Raza',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Sexo',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='Tamaño',
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='pet',
            name='hair',
            field=models.CharField(choices=[('S', 'Corto'), ('M', 'Mediano'), ('L', 'Largo')], default='S', max_length=50, verbose_name='Pelaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='in_adopt',
            field=models.BooleanField(default=None, verbose_name='En Adopción'),
        ),
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default='helena', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.CharField(blank=True, max_length=50, verbose_name='Dueño'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default=('M', 'Macho'), max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default=('M', 'Mediano'), max_length=1, verbose_name='Tamaño'),
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Gato'), ('dog', 'Perro')], default=('cat', 'Gato'), max_length=3, verbose_name='Especie'),
        ),
    ]
