# Generated by Django 5.1 on 2025-06-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_pet_dueño_remove_pet_en_adopción_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='bio',
            field=models.TextField(help_text='Datos de la mascota', max_length=250),
        ),
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, help_text='DD/MM/AAAA', null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hair',
            field=models.CharField(blank=True, choices=[('S', 'Corto'), ('M', 'Mediano'), ('L', 'Largo')], default='M', max_length=50, verbose_name='Pelaje'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='in_adopt',
            field=models.BooleanField(default=False, verbose_name='En Adopción'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default='Macho', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default='M', max_length=1, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Gato'), ('dog', 'Perro')], default='Gato', max_length=3, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('OK', 'Normal'), ('SK', 'Enfermo'), ('DF', 'Fallecido')], default='Normal', max_length=2),
        ),
    ]
