# Generated by Django 4.2.23 on 2025-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_hair_alter_pet_sex_alter_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default=('M', 'Mediano'), max_length=1, null=True),
        ),
    ]
