# Generated by Django 4.2.23 on 2025-06-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_bio_alter_pet_birth_date_alter_pet_hair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='in_adopt',
            field=models.BooleanField(default=True, verbose_name='En Adopción'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.CharField(blank=True, max_length=1, verbose_name='Dueño'),
        ),
    ]
