# Generated by Django 4.2.23 on 2025-07-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_in_adopt_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateTimeField(blank=True, help_text='DD/MM/AAAA', null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
