# Generated by Django 4.2.23 on 2025-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default=('M', 'Macho'), max_length=5),
        ),
    ]
