# Generated by Django 4.2.23 on 2025-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, help_text='DD/MM/AAAA', null=True, verbose_name='Fecha nacimiento'),
        ),
    ]
