# Generated by Django 4.2.23 on 2025-07-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_service_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='file',
        ),
    ]
