# Generated by Django 4.2.23 on 2025-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='file',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
