# Generated by Django 4.2.23 on 2025-07-16 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0008_remove_pet_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='owned_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
