# Generated by Django 4.2.23 on 2025-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_pet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('OK', 'Normal'), ('SK', 'Enfermo'), ('DF', 'Fallecido')], default='Normal', max_length=2, null=True),
        ),
    ]
