# Generated by Django 4.2.23 on 2025-07-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_remove_pet_owner_pet_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owners',
        ),
    ]
