# Generated by Django 4.2.23 on 2025-07-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, help_text='DD/MM/AAAA', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hair',
            field=models.CharField(blank=True, choices=[('S', 'Corto'), ('M', 'Mediano'), ('L', 'Largo')], default=('M', 'Mediano'), max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='in_adopt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], default=('M', 'Macho'), max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande')], default=('M', 'Mediano'), max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('cat', 'Gato'), ('dog', 'Perro')], default='Gato', max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('OK', 'Normal'), ('SK', 'Enfermo'), ('DF', 'Fallecido')], default=('SK', 'Enfermo'), max_length=2, null=True),
        ),
    ]
