# Generated by Django 4.2.23 on 2025-07-16 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0010_delete_service_remove_pet_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.pet')),
            ],
            options={
                'unique_together': {('pet', 'owner', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='owners',
            field=models.ManyToManyField(related_name='owned_pets', through='pets.Ownership', to=settings.AUTH_USER_MODEL),
        ),
    ]
