# Generated by Django 5.2.1 on 2025-06-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='img',
        ),
        migrations.AddField(
            model_name='picture',
            name='file',
            field=models.ImageField(default='', upload_to='picture'),
            preserve_default=False,
        ),
    ]
