name: Deploy to server

on:
    push:
        branches:
            - "main"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup_SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Git pull
              run: bash deploy.sh
              env:
                  USER: ${{ secrets.SSH_USER }}
                  IP: ${{ secrets.SSH_IP }}