name: Deploy to server

on:
    push:
        branches:
            - "main"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            # - name: Setup_SSH
            #   uses: webfactory/ssh-agent@v0.9.0
            #   with:
            #       ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Update_repo
              uses: yacenturion/ssh-fetch-pull@v1
              with:
                  HOST: ${{ secrets.SSH_IP }}
                  USERNAME: ${{ secrets.SSH_USER }}
                  SSH_KEY: ${{ secrets.SSH_KEY }}
                  DEST_PATH: ${{ vars.PATH }}
                  RUN_BEFORE: "echo 'Starting deployment...'"
                  RUN_AFTER: "systemctl restart nginx; ls -la"

            # - name: Git pull
            #   run: bash deploy.sh
            #   env:
            #     USER:
            #     IP:
